Repository ByteTalkers/FT_IRC, pull requests merged in 2024-02, with the labels that each got.

#2 [테스트] #1
  test/test.txt
Labels: documentation

#8 [feat] Message/Response 클래스 추가
  Message/Message.cpp
  Message/Message.hpp
  Response/Response.cpp
  Response/Response.hpp
  test/messageTest.cpp
Labels: ✨ feat

#10 [feat] Channel 클래스 추가
  Channel/Channel.cpp
  Channel/Channel.hpp
  Client/Client.cpp
  Client/Client.hpp
Labels: ✨ feat

#14 feat: Client 및 Server 기능 추가
  Channel/Channel.hpp
  Client/Client.cpp
  Client/Client.hpp
  Makefile
  Server/Server.cpp
  Server/Server.hpp
Labels: ✨ feat

#15 [feat] Response - 유저 등록 기본 응답 추가
  Client/Client.cpp
  Client/Client.hpp
  Response/Response.cpp
  Response/Response.hpp
  Server/Server.cpp
  Server/Server.hpp
  test/Makefile
  test/responseTest.cpp
  utils/utils.cpp
  utils/utils.hpp
Labels: ✨ feat

#17 feat: Message - 로그인을 위한 기능 추가
  Client/Client.cpp
  Client/Client.hpp
  Message/Message.cpp
  Message/Message.hpp
Labels: ✨ feat

#18 feat: ping 응답 추가
  Channel/Channel.cpp
  Client/Client.cpp
  Client/Client.hpp
  Makefile
  Message/Message.cpp
  Message/Message.hpp
  Response/Response.cpp
  Response/Response.hpp
Labels: ✨ feat

#23 [feat] response 응답 에러 추가 + 테스트 코드 추가
  Client/Client.cpp
  Client/Client.hpp
  Message/Message.cpp
  Response/Response.cpp
  Response/Response.hpp
  Server/Server.cpp
  ircserv
Labels: ✨ feat

#30 [feat] user 등록 + 파싱 로직 수정
  Client/Client.cpp
  Client/Client.hpp
  Makefile
  Message/Command.cpp
  Message/Command.hpp
  Message/Message.cpp
  Message/Message.hpp
  Message/nick.cpp
  Message/parsing.cpp
  Message/pass.cpp
  Message/user.cpp
  Response/Response.cpp
Labels: ✨ feat

#33 [feat] 유저 등록 응답 구현
  Client/Client.cpp
  Message/Command.cpp
  Message/Command.hpp
  Message/Message.cpp
  Message/Message.hpp
  Message/mode.cpp
  Message/parsing.cpp
  Message/ping.cpp
  Message/whois.cpp
  Response/Response.cpp
  Response/Response.hpp
Labels: ✨ feat

#36 [fix] make 목록 수정, 안쓰는 인자 void 처리
  Makefile
  Message/mode.cpp
  Message/ping.cpp
  Message/whois.cpp
Labels: ❗️ bug / fix

#40 [feat] join 메서드 기능 추가
  Client/Client.cpp
  Client/Client.hpp
  Message/join.cpp
  utils/utils.cpp
  utils/utils.hpp
Labels: ✨ feat

#44 [feat] message privmsg, mode, topic
  Channel/Channel.cpp
  Channel/Channel.hpp
  Client/Client.cpp
  Makefile
  Message/Command.cpp
  Message/Command.hpp
  Message/Message.cpp
  Message/Message.hpp
  Message/join.cpp
  Message/mode.cpp
  Message/parsing.cpp
  Message/ping.cpp
  Message/privmsg.cpp
  Message/topic.cpp
  Message/user.cpp
  Message/whois.cpp
  Response/Response.cpp
  Response/Response.hpp
  Server/Server.cpp
  Server/Server.hpp
  Server/utils.cpp
  ircserv
Labels: ✨ feat

#48 [refactor] Response - 함수명 전부 대문자로 변경, test 폴더 삭제
  Message/user.cpp
  Message/whois.cpp
  Response/Response.cpp
  Response/Response.hpp
  test/Makefile
  test/messageTest.cpp
  test/responseTest.cpp
Labels: 👨‍💻 refactor

#49 feat: Message - topic mode
  Channel/Channel.cpp
  Channel/Channel.hpp
  Message/mode.cpp
  Message/privmsg.cpp
  Message/topic.cpp
  ircserv
Labels: ✨ feat

#53 feat: Client, Server 새 기능 추가 & Response 조정
  Channel/Channel.cpp
  Channel/Channel.hpp
  Client/Client.cpp
  Client/Client.hpp
  Makefile
  Message/mode.cpp
  Message/ping.cpp
  Message/privmsg.cpp
  Message/topic.cpp
  Message/whois.cpp
  Response/Response.cpp
  Response/Response.hpp
  Server/Server.cpp
  Server/Server.hpp
  main.cpp
Labels: ❗️ bug / fix, ✨ feat, 👨‍💻 refactor

#52 [feat, refactor] Response - join who 응답 추가 + Response 형식 변경
  Channel/Channel.cpp
  Message/join.cpp
  Message/mode.cpp
  Message/ping.cpp
  Message/privmsg.cpp
  Message/topic.cpp
  Message/user.cpp
  Message/whois.cpp
  Response/Response.cpp
  Response/Response.hpp
Labels: ✨ feat, 👨‍💻 refactor

#59 [feat] Message 커맨드 처리part quit
  Channel/Channel.cpp
  Channel/Channel.hpp
  Makefile
  Message/Message.cpp
  Message/Message.hpp
  Message/join.cpp
  Message/part.cpp
  Message/quit.cpp
  utils/utils.hpp
Labels: ✨ feat

#57 [feat] Message - nick 실행부 추가
  Client/Client.cpp
  Client/Client.hpp
  Message/Message.hpp
  Message/mode.cpp
  Message/nick.cpp
Labels: ✨ feat

#61 fix : 소소한 오류 및 makefile fclean 실행 후 pull
  Channel/Channel.cpp
  Channel/Channel.hpp
  Makefile
  Message/mode.cpp
  Message/part.cpp
  Message/quit.cpp
  ircserv
Labels: ❗️ bug / fix

#71 [fix] 유저 등록 안되던 문제 해결
  Makefile
  Message/Message.cpp
Labels: ❗️ bug / fix

#69 [fix] Message - mode 로직 수정
  Channel/Channel.cpp
  Channel/Channel.hpp
  Message/mode.cpp
  Response/Response.cpp
  Response/Response.hpp
Labels: ❗️ bug / fix, ✨ feat

#75 [fix] Client, Channel - 초기화 문제 수정
  Channel/Channel.cpp
  Client/Client.cpp
  Message/nick.cpp
Labels: ❗️ bug / fix

#76 [fix] nick 중복 에러 수정
  Message/nick.cpp
  Response/Response.cpp
  Server/Server.cpp
  Server/Server.hpp
Labels: ❗️ bug / fix

#79 [feat] Message join 시 요청하는 mode who 응답 추가
  Makefile
  Message/Message.cpp
  Message/Message.hpp
  Message/mode.cpp
  Message/who.cpp
  Message/whois.cpp
  Response/Response.cpp
  Response/Response.hpp
Labels: ✨ feat

#81 [refactor] Message - client.setWriteType() 위치 변경
  Message/Message.cpp
  Message/invite.cpp
  Message/mode.cpp
  Message/nick.cpp
  Message/pass.cpp
  Message/ping.cpp
  Message/privmsg.cpp
  Message/topic.cpp
  Message/user.cpp
  Message/who.cpp
Labels: 👨‍💻 refactor

#83 Fix: Message join 메서드 수정
  Channel/Channel.cpp
  Channel/Channel.hpp
  Makefile
  Message/Command.cpp
  Message/join.cpp
  Message/mode.cpp
  Response/Response.cpp
  Response/Response.hpp
  Server/Server.cpp
  Server/Server.hpp
Labels: ❗️ bug / fix

#86 fix / refactor: timeout용 메소드 삭제
  Server/Server.cpp
  Server/Server.hpp
Labels: ❗️ bug / fix, 👨‍💻 refactor

#87 [fix] Message - mode 에러 수정
  Message/Command.cpp
  Message/Command.hpp
  Message/Message.cpp
  Message/Message.hpp
  Message/mode.cpp
  Response/Response.cpp
Labels: ❗️ bug / fix

#92 [fix] Server - delEmptyChannel() 추가
  Channel/Channel.cpp
  Channel/Channel.hpp
  Message/Message.cpp
  Message/quit.cpp
  Server/Server.cpp
  Server/Server.hpp
Labels: ❗️ bug / fix, ✨ feat, 👨‍💻 refactor, 🔖 Comment

#94 Fix: part 메서드 수정
  Channel/Channel.hpp
  Makefile
  Message/part.cpp
Labels: ❗️ bug / fix

#97 feat: part일때 채널삭제 가능성 추가
  Message/Message.cpp
Labels: ✨ feat

#98 [fix] Message - mode, topic 케이스 추가
  Message/mode.cpp
  Message/topic.cpp
  Response/Response.cpp
  Response/Response.hpp
Labels: ❗️ bug / fix

#99 [refactor] Command - paramscount 변수 삭제 및 getParamscount 함수 변경
  Message/Command.cpp
  Message/Command.hpp
Labels: 👨‍💻 refactor

#103 [refactor] Command, Message - Command 관리 방식 변경
  Message/Message.cpp
  Message/Message.hpp
  Message/parsing.cpp
Labels: 👨‍💻 refactor

#104 [fix] Message - mode o 오류 수정, Channel - addSendmsg 형식 변경
  Channel/Channel.cpp
  Channel/Channel.hpp
  Message/join.cpp
  Message/kick.cpp
  Message/mode.cpp
  Message/part.cpp
  Message/privmsg.cpp
  Message/topic.cpp
Labels: ❗️ bug / fix

#113 [Feat] 봇 기능으로 로또 번호 출력 기능
  Channel/Channel.cpp
  Message/Message.hpp
  Message/privmsg.cpp
Labels: ✨ feat

#114 [fix] Message - mode, parsing, user, nick 수정
  Channel/Channel.cpp
  Client/Client.cpp
  Client/Client.hpp
  Message/join.cpp
  Message/kick.cpp
  Message/mode.cpp
  Message/nick.cpp
  Message/parsing.cpp
  Message/part.cpp
  Message/privmsg.cpp
  Message/topic.cpp
  Message/user.cpp
  Response/Response.cpp
Labels: ❗️ bug / fix

#116 [fix] 채널에 메시지 보내는 prefix 오류 수정
  Channel/Channel.cpp
  Message/join.cpp
  Message/privmsg.cpp
  Server/Server.cpp
Labels: ❗️ bug / fix
